// src/renderer/components/HistoryPanel/HistoryHeader.tsx
import { Show } from 'solid-js'
import { Input } from '../ui/input'
import { LoadingBadge } from '../ui/loading-badge'
import { PanelActions, PanelHeader, PanelHeaderGroup, PanelSubtitle, PanelTitle } from '../ui/panel'

interface HistoryHeaderProps {
  total?: number
  visibleTotal?: number
  loading: boolean
  filter: string
  onFilterChange: (value: string) => void
  showFilter: boolean
  branchFilterActive?: boolean
  selectedBranchCount?: number
}

function subtitle(props: HistoryHeaderProps): string {
  const visible = props.visibleTotal ?? props.total
  if (!visible && !props.total) {
    return 'Repository timeline'
  }
  const count = visible ?? 0
  const commitLabel = `${count} commit${count === 1 ? '' : 's'}`
  if (props.branchFilterActive && (props.selectedBranchCount ?? 0) > 0) {
    return `${commitLabel} · filtered`
  }
  return `${commitLabel} · all branches`
}

export function HistoryHeader(props: HistoryHeaderProps) {
  return (
    <PanelHeader class="gap-3">
      <PanelHeaderGroup>
        <PanelTitle class="text-foreground">Timeline</PanelTitle>
        <PanelSubtitle>{subtitle(props)}</PanelSubtitle>
      </PanelHeaderGroup>

      <PanelActions>
        <Show when={props.showFilter}>
          <Input
            value={props.filter}
            onInput={(event) => props.onFilterChange(event.currentTarget.value)}
            placeholder="filter commits…"
            class="h-7 w-40"
          />
        </Show>
        <Show when={props.loading}>
          <LoadingBadge />
        </Show>
      </PanelActions>
    </PanelHeader>
  )
}

// src/renderer/features/history/HistoryHeader.tsx
import { Button } from '../../components/ui/button'
import { Input } from '../../components/ui/input'
import { LoadingBadge } from '../../components/ui/loading-badge'

interface HistoryHeaderProps {
  loadedCount: number
  visibleTotal?: number
  loading: boolean
  loadingMore?: boolean
  hasMore?: boolean
  onLoadMore?: () => void
  filter: string
  onFilterChange: (value: string) => void
  showFilter: boolean
  visibleBranchCount?: number
}

function subtitle(props: HistoryHeaderProps): string {
  const visible = props.visibleTotal ?? props.loadedCount
  if (!visible && props.loadedCount === 0) {
    return 'Repository timeline'
  }
  const count = visible ?? 0
  const commitLabel = `${count.toLocaleString()} commit${count === 1 ? '' : 's'}`
  const visibleBranchCount = props.visibleBranchCount ?? 0
  const filterLabel =
    visibleBranchCount === 0
      ? ' · no branches visible'
      : ` · ${visibleBranchCount} branch${visibleBranchCount === 1 ? '' : 'es'} visible`
  if (props.hasMore) {
    return `${commitLabel}${filterLabel} · ${props.loadedCount.toLocaleString()} loaded · more available`
  }
  return `${commitLabel}${filterLabel}`
}

export function HistoryHeader(props: HistoryHeaderProps) {
  return (
    <div className="flex min-h-[46px] shrink-0 items-center gap-2.5 border-b py-1.5 pl-3.5 pr-2">
      <div className="min-w-0">
        <div className="text-[15px] font-semibold">Timeline</div>
        <div className="truncate text-[13px] text-muted-foreground">{subtitle(props)}</div>
      </div>
      <div className="flex-1" />
      {props.loading || props.loadingMore ? <LoadingBadge /> : null}
      {props.hasMore && props.onLoadMore ? (
        <Button
          size="sm"
          variant="outline"
          className="h-8"
          disabled={props.loadingMore || props.loading}
          onClick={() => props.onLoadMore?.()}
        >
          {props.loadingMore ? 'Loading…' : 'Load more'}
        </Button>
      ) : null}
      {props.showFilter ? (
        <Input
          value={props.filter}
          onChange={(event) => props.onFilterChange(event.currentTarget.value)}
          placeholder="Filter commits…"
          aria-label="Filter commits"
          className="h-[34px] w-60 rounded-[var(--r-sm)] bg-background"
        />
      ) : null}
    </div>
  )
}
