// src/renderer/components/ui/separator.tsx
import type { HTMLAttributes } from 'react'
import { cn } from '@/lib/utils'

function Separator(
  props: HTMLAttributes<HTMLDivElement> & { orientation?: 'horizontal' | 'vertical' }
) {
  const { className, orientation = 'horizontal', ...rest } = props
  return (
    <div
      data-slot="separator"
      data-orientation={orientation}
      className={cn(
        'shrink-0 bg-border data-[orientation=horizontal]:h-px data-[orientation=horizontal]:w-full data-[orientation=vertical]:h-full data-[orientation=vertical]:w-px',
        className
      )}
      {...rest}
    />
  )
}

export { Separator }

// src/renderer/solid/components/ui/separator.tsx
import { Separator as SeparatorPrimitive } from '@kobalte/core/separator'
import { type ComponentProps, splitProps } from 'solid-js'
import { cn } from '@/lib/utils'

function Separator(props: ComponentProps<typeof SeparatorPrimitive>) {
  const [local, rest] = splitProps(props, ['class', 'orientation'])
  return (
    <SeparatorPrimitive
      data-slot="separator"
      orientation={local.orientation ?? 'horizontal'}
      class={cn(
        'shrink-0 bg-border data-[orientation=horizontal]:h-px data-[orientation=horizontal]:w-full data-[orientation=vertical]:h-full data-[orientation=vertical]:w-px',
        local.class
      )}
      {...rest}
    />
  )
}

export { Separator }
