// src/renderer/solid/App.tsx
import type { PersistedTabs } from '@shared/schemas/ipc'
import { createEffect, createSignal, For, onMount, Show } from 'solid-js'
import { OnboardingScreen } from './components/OnboardingScreen'
import { TabBar } from './components/TabBar'
import { Toaster } from './components/ui/sonner'
import { useOnboarding } from './hooks/useOnboarding'
import { useTabs } from './hooks/useTabs'
import { TabView } from './TabView'

export default function App() {
  const onboarding = useOnboarding()
  const [persistedTabs, setPersistedTabs] = createSignal<PersistedTabs | null>(null)

  onMount(() => {
    window.electronAPI
      .getPersistedTabs()
      .then((state) => {
        setPersistedTabs({ tabs: [...state.tabs], activeIndex: state.activeIndex })
      })
      .catch((error: unknown) => {
        console.error('[app] failed to load persisted tabs', error)
        setPersistedTabs({ tabs: [], activeIndex: 0 })
      })
  })

  return (
    <Show
      when={onboarding.onboardingComplete() !== null && persistedTabs() !== null}
      fallback={
        <div class="flex h-screen items-center justify-center bg-background text-foreground">
          <div class="animate-pulse text-xs text-muted-foreground">Loading...</div>
        </div>
      }
    >
      <Show
        when={onboarding.onboardingComplete()}
        fallback={
          <OnboardingScreen
            workingDirectory={onboarding.workingDirectory()}
            discoveredRepos={onboarding.discoveredRepos()}
            loading={onboarding.loading()}
            error={onboarding.error()}
            onSelectDirectory={onboarding.addWorkspace}
            onComplete={onboarding.completeOnboarding}
            onOpenRepo={async (path) => {
              await onboarding.completeOnboarding()
              try {
                await window.electronAPI.openRepo(path)
              } catch (error) {
                console.error('[onboarding] openRepo failed', { path, error })
              }
            }}
          />
        }
      >
        <TabsShell persisted={persistedTabs() as PersistedTabs} onboarding={onboarding} />
      </Show>
    </Show>
  )
}

interface TabsShellProps {
  persisted: PersistedTabs
  onboarding: ReturnType<typeof useOnboarding>
}

function TabsShell(props: TabsShellProps) {
  const {
    tabs,
    activeTabId,
    setActiveTabId,
    tabDescriptors,
    newTab,
    closeTab,
    reportTabRepo,
    requestOpenRepo,
    persistedSnapshot,
    initialRepoPath
  } = useTabs(props.persisted)
  const [recentRepos, setRecentRepos] = createSignal<string[]>([])

  onMount(() => {
    window.electronAPI.getRecentRepos().then(setRecentRepos)
  })

  createEffect(() => {
    window.electronAPI.setPersistedTabs(persistedSnapshot()).catch((error: unknown) => {
      console.warn('[app] failed to persist tab state', error)
    })
  })

  return (
    <div class="flex h-screen flex-col bg-background text-foreground">
      <Toaster richColors position="bottom-right" />
      <TabBar
        tabs={tabDescriptors()}
        activeTabId={activeTabId()}
        onSelect={setActiveTabId}
        onClose={closeTab}
        onNew={newTab}
      />

      <div class="relative flex min-h-0 flex-1 flex-col overflow-hidden">
        <For each={tabs()}>
          {(tab) => (
            <div
              class={
                tab.id === activeTabId()
                  ? 'flex min-h-0 flex-1 flex-col'
                  : 'pointer-events-none invisible absolute inset-0 flex min-h-0 flex-col'
              }
              aria-hidden={tab.id !== activeTabId()}
            >
              <TabView
                tabId={tab.id}
                initialRepoPath={initialRepoPath(tab.id)}
                recentRepos={recentRepos()}
                discoveredRepos={props.onboarding.discoveredRepos()}
                workspaces={props.onboarding.workspaces()}
                activeWorkspace={props.onboarding.activeWorkspace()}
                onSwitchWorkspace={props.onboarding.switchWorkspace}
                onAddWorkspace={props.onboarding.addWorkspace}
                onRemoveWorkspace={props.onboarding.removeWorkspace}
                onReportRepo={reportTabRepo}
                onRequestOpenRepo={requestOpenRepo}
              />
            </div>
          )}
        </For>
      </div>
    </div>
  )
}

// src/renderer/app/App.tsx
import type { PersistedTabs } from '@shared/schemas/ipc'
import { type ReactNode, useCallback, useEffect, useMemo, useState } from 'react'
import { PortalContainerProvider } from '../components/ui/portal-container'
import { Toaster } from '../components/ui/sonner'
import { OnboardingScreen } from '../features/onboarding/OnboardingScreen'
import { useOnboarding } from '../features/onboarding/useOnboarding'
import { useTabs } from '../hooks/useTabs'
import { RepoRail } from '../shell/RepoRail'
import { Titlebar } from '../shell/Titlebar'
import type { WorkspaceCatalog } from './NewTab'
import { TabView } from './TabView'

export default function App() {
  const onboarding = useOnboarding()
  const [persistedTabs, setPersistedTabs] = useState<PersistedTabs | null>(null)
  const [onboardingRepoPath, setOnboardingRepoPath] = useState<string | null>(null)

  useEffect(() => {
    window.electronAPI
      .getPersistedTabs()
      .then((state) => {
        setPersistedTabs({ tabs: [...state.tabs], activeIndex: state.activeIndex })
      })
      .catch((error: unknown) => {
        console.error('[app] failed to load persisted tabs', error)
        setPersistedTabs({ tabs: [null], activeIndex: 0 })
      })
  }, [])

  if (onboarding.onboardingComplete === null || persistedTabs === null) {
    return (
      <div className="flex h-screen items-center justify-center bg-background text-foreground">
        <div className="animate-pulse text-xs text-muted-foreground">Loading...</div>
      </div>
    )
  }

  if (!onboarding.onboardingComplete) {
    return (
      <OnboardingScreen
        workingDirectory={onboarding.workingDirectory}
        discoveredRepos={onboarding.discoveredRepos}
        loading={onboarding.loading}
        error={onboarding.error}
        onSelectDirectory={onboarding.addWorkspace}
        onComplete={onboarding.completeOnboarding}
        onOpenRepo={async (path) => {
          try {
            setOnboardingRepoPath(path)
            setPersistedTabs({ tabs: [path], activeIndex: 0 })
            await onboarding.completeOnboarding()
          } catch (error) {
            console.error('[onboarding] openRepo failed', { path, error })
          }
        }}
      />
    )
  }

  return (
    <TabsShell
      persisted={
        onboardingRepoPath ? { tabs: [onboardingRepoPath], activeIndex: 0 } : persistedTabs
      }
      onboarding={onboarding}
    />
  )
}

interface TabsShellProps {
  persisted: PersistedTabs
  onboarding: ReturnType<typeof useOnboarding>
}

function TabsShell(props: TabsShellProps) {
  const {
    tabs,
    activeTabId,
    setActiveTabId,
    tabDescriptors,
    newTab,
    closeTab,
    openRepoInTab,
    confirmRepoOpen,
    cancelRepoOpen,
    persistedSnapshot
  } = useTabs(props.persisted)
  const [recentRepos, setRecentRepos] = useState<string[]>([])
  const [activatedTabIds, setActivatedTabIds] = useState<Set<string>>(new Set([activeTabId]))

  useEffect(() => {
    window.electronAPI
      .getRecentRepos()
      .then(setRecentRepos)
      .catch((error: unknown) => {
        console.error('[app] failed to load recent repos', error)
        setRecentRepos([])
      })
  }, [])

  const rescanWorkspace = props.onboarding.rescanWorkingDirectory
  const refreshCatalog = useCallback(async () => {
    const [recent] = await Promise.all([
      window.electronAPI.getRecentRepos().catch((error: unknown) => {
        console.error('[app] failed to refresh recent repos', error)
        return null
      }),
      rescanWorkspace().catch((error: unknown) => {
        console.error('[app] failed to rescan the workspace', error)
      })
    ])
    if (recent) {
      setRecentRepos(recent)
    }
  }, [rescanWorkspace])

  useEffect(() => {
    window.electronAPI.setPersistedTabs(persistedSnapshot).catch((error: unknown) => {
      console.warn('[app] failed to persist tab state', error)
    })
  }, [persistedSnapshot])

  useEffect(() => {
    const id = activeTabId
    setActivatedTabIds((previous) => {
      if (previous.has(id)) {
        return previous
      }
      return new Set([...previous, id])
    })
  }, [activeTabId])

  const loadedTabDescriptors = useMemo(() => {
    const activated = activatedTabIds
    const active = activeTabId
    return tabDescriptors.map((tab) => ({
      ...tab,
      loaded: !tab.hasRepo || tab.id === active || activated.has(tab.id)
    }))
  }, [activatedTabIds, activeTabId, tabDescriptors])

  const workspaceCatalog = useMemo<WorkspaceCatalog>(
    () => ({
      recentRepos,
      discoveredRepos: props.onboarding.discoveredRepos,
      workspaces: props.onboarding.workspaces,
      activeWorkspace: props.onboarding.activeWorkspace,
      switchWorkspace: props.onboarding.switchWorkspace,
      addWorkspace: props.onboarding.addWorkspace,
      removeWorkspace: props.onboarding.removeWorkspace,
      refresh: refreshCatalog
    }),
    [
      refreshCatalog,
      recentRepos,
      props.onboarding.discoveredRepos,
      props.onboarding.workspaces,
      props.onboarding.activeWorkspace,
      props.onboarding.switchWorkspace,
      props.onboarding.addWorkspace,
      props.onboarding.removeWorkspace
    ]
  )

  return (
    <div className="flex h-screen flex-col bg-chrome text-foreground">
      <Toaster richColors position="bottom-right" />
      <Titlebar />

      <div className="grid min-h-0 flex-1 grid-cols-[64px_minmax(0,1fr)]">
        <RepoRail
          tabs={loadedTabDescriptors}
          activeTabId={activeTabId}
          onSelect={setActiveTabId}
          onClose={closeTab}
          onNew={newTab}
        />

        <div className="relative flex min-h-0 flex-col overflow-hidden">
          {tabs.map((tab) => {
            const tabActive = tab.id === activeTabId
            const tabLoaded = tabActive || activatedTabIds.has(tab.id)
            return (
              <TabOwner key={tab.id} active={tabActive}>
                {tabLoaded ? (
                  <TabView
                    tab={tab}
                    tabActive={tabActive}
                    catalog={workspaceCatalog}
                    onOpenRepo={openRepoInTab}
                    onRepoOpened={confirmRepoOpen}
                    onRepoOpenFailed={cancelRepoOpen}
                  />
                ) : null}
              </TabOwner>
            )
          })}
        </div>
      </div>
    </div>
  )
}

function TabOwner(props: { active: boolean; children: ReactNode }) {
  const [container, setContainer] = useState<HTMLDivElement | null>(null)

  return (
    <div
      ref={setContainer}
      className={
        props.active
          ? 'flex h-full min-h-0 flex-col'
          : 'pointer-events-none invisible absolute inset-0 flex min-h-0 flex-col'
      }
      aria-hidden={!props.active}
    >
      <PortalContainerProvider container={container}>{props.children}</PortalContainerProvider>
    </div>
  )
}
