// src/renderer/features/commit/CommitPanel.tsx
import { Loader2Icon } from 'lucide-react'
import type { ChangeEvent, ReactNode } from 'react'
import { useEffect, useRef, useState } from 'react'
import { cn } from '@/lib/utils'

interface CommitPanelProps {
  onCommit: (message: string) => Promise<boolean>
  onAmend: (
    message: string,
    droppedHeadPaths: string[],
    droppedHeadHunks: { file: string; hunks: string[] }[],
    expectedHead: string
  ) => Promise<boolean>
  expectedHead: string | undefined
  loadHeadMessage: () => Promise<string | null>
  amendAvailable: boolean
  amendDisabled: boolean
  loading: boolean
  branch: string
  stagedCount: number
  ahead?: number
  onAmendChange?: (amend: boolean) => void
  droppedHeadPaths?: string[]
  droppedHeadHunks?: { file: string; hunks: string[] }[]
  prefillMessage?: string
  concludesMerge?: boolean
  commitBlockedReason?: string
}

const MAX_SUBJECT_LENGTH = 72

export function CommitPanel(props: CommitPanelProps) {
  const [message, setMessage] = useState('')
  const [amend, setAmend] = useState(false)
  const [savedDraft, setSavedDraft] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const messageRef = useRef(message)
  const amendRef = useRef(amend)
  const amendLoadGeneration = useRef(0)
  const submittingRef = useRef(false)
  const appliedPrefill = useRef<string | undefined>(undefined)

  useEffect(() => {
    const prefill = props.prefillMessage
    if (prefill === appliedPrefill.current) {
      return
    }
    const userTyped =
      messageRef.current.trim().length > 0 && messageRef.current !== appliedPrefill.current
    appliedPrefill.current = prefill
    if (userTyped || amendRef.current) {
      return
    }
    messageRef.current = prefill ?? ''
    setMessage(prefill ?? '')
  }, [props.prefillMessage])

  const handleAmendToggle = async (event: ChangeEvent<HTMLInputElement>) => {
    if (event.currentTarget.checked) {
      setSavedDraft(message)
      amendRef.current = true
      setAmend(true)
      props.onAmendChange?.(true)
      const generation = amendLoadGeneration.current + 1
      amendLoadGeneration.current = generation
      const headMessage = await props.loadHeadMessage()
      if (headMessage !== null && amendRef.current && amendLoadGeneration.current === generation) {
        messageRef.current = headMessage
        setMessage(headMessage)
      }
    } else {
      amendLoadGeneration.current += 1
      amendRef.current = false
      setAmend(false)
      props.onAmendChange?.(false)
      messageRef.current = savedDraft
      setMessage(savedDraft)
    }
  }

  const handleCommit = async () => {
    if (submittingRef.current) {
      return
    }
    const submittedMessage = messageRef.current
    const trimmed = submittedMessage.trim()
    if (!trimmed) {
      return
    }
    submittingRef.current = true
    setSubmitting(true)
    try {
      let success: boolean
      if (amendRef.current) {
        const expectedHead = props.expectedHead
        if (!expectedHead) {
          return
        }
        success = await props.onAmend(
          trimmed,
          props.droppedHeadPaths ?? [],
          props.droppedHeadHunks ?? [],
          expectedHead
        )
      } else {
        success = await props.onCommit(trimmed)
      }
      if (success) {
        setMessage((current) => {
          if (current !== submittedMessage) {
            return current
          }
          messageRef.current = ''
          return ''
        })
        amendRef.current = false
        setAmend(false)
        props.onAmendChange?.(false)
      }
    } finally {
      submittingRef.current = false
      setSubmitting(false)
    }
  }

  const subjectLength = (message.split('\n')[0] ?? '').length
  const subjectWarn = subjectLength > MAX_SUBJECT_LENGTH
  const concludesMerge = Boolean(props.concludesMerge) && !amend
  const commitLabel = amend
    ? 'Amend'
    : concludesMerge
      ? 'Commit merge'
      : props.stagedCount > 0
        ? `Commit ${props.stagedCount} file${props.stagedCount === 1 ? '' : 's'}`
        : 'Commit'
  const loading = props.loading || submitting
  const hasDroppedFiles = amend && (props.droppedHeadPaths?.length ?? 0) > 0
  const commitBlocked = Boolean(props.commitBlockedReason)
  const commitDisabled =
    !message.trim() ||
    loading ||
    commitBlocked ||
    (!amend && !concludesMerge && props.stagedCount === 0) ||
    (amend && !props.expectedHead)

  return (
    <div className="shrink-0 border-t px-3 pb-3 pt-2.5">
      <div className="rounded-[var(--r-md)] border bg-background p-2 transition-shadow focus-within:border-[var(--brand-line)] focus-within:shadow-[0_0_0_3px_var(--brand-soft)]">
        <textarea
          value={message}
          onChange={(event) => {
            const nextMessage = event.currentTarget.value
            amendLoadGeneration.current += 1
            messageRef.current = nextMessage
            setMessage(nextMessage)
          }}
          placeholder="Describe your changes…"
          aria-label="Commit message"
          rows={2}
          className="max-h-36 min-h-[50px] w-full resize-none border-0 bg-transparent px-1.5 py-1 text-sm text-foreground outline-none"
        />
        {commitBlocked ? (
          <p className="px-1.5 pb-1 text-xs text-amber-foreground">{props.commitBlockedReason}</p>
        ) : null}
        {hasDroppedFiles ? (
          <p className="px-1.5 pb-1 text-xs text-amber-foreground">
            Amend restores dropped files from the parent commit. Staged changes in dropped files
            will also be excluded.
          </p>
        ) : null}
        <div className="flex items-center gap-2 px-1 pb-0.5 pt-1.5">
          <div className="flex items-center gap-1.5">
            <MetaChip color="var(--blue)">{props.branch}</MetaChip>
            {props.stagedCount > 0 && (
              <MetaChip color="var(--green)">{props.stagedCount} staged</MetaChip>
            )}
            {(props.ahead ?? 0) > 0 && <MetaChip color="var(--green)">↑{props.ahead}</MetaChip>}
            {props.amendAvailable && (
              <label className="flex items-center gap-1.5 text-xs text-muted-foreground">
                <input
                  type="checkbox"
                  checked={amend}
                  disabled={props.amendDisabled || loading}
                  onChange={handleAmendToggle}
                  aria-label="Amend last commit"
                  className="size-3.5 accent-[var(--brand)]"
                />
                Amend last commit
              </label>
            )}
          </div>
          <div className="flex-1" />
          <span
            className={cn(
              'text-xs tabular-nums',
              subjectWarn ? 'text-destructive' : 'text-muted-foreground'
            )}
          >
            {subjectLength} / {MAX_SUBJECT_LENGTH}
          </span>
          <button
            type="button"
            onClick={handleCommit}
            disabled={commitDisabled}
            className="inline-flex h-8 items-center gap-1.5 rounded-[var(--r-sm)] bg-brand px-3 font-semibold text-brand-foreground transition-colors hover:bg-[var(--brand-strong)] disabled:opacity-50"
          >
            {loading ? (
              <>
                <Loader2Icon className="size-3.5 animate-spin" />
                Committing…
              </>
            ) : (
              commitLabel
            )}
          </button>
        </div>
      </div>
    </div>
  )
}

function MetaChip(props: { color: string; children: ReactNode }) {
  return (
    <span
      className="inline-flex h-6 items-center gap-1 rounded-full px-2.5 text-xs font-semibold"
      style={{
        color: props.color,
        backgroundColor: `color-mix(in oklch, ${props.color} 16%, transparent)`
      }}
    >
      {props.children}
    </span>
  )
}

// src/renderer/solid/components/CommitPanel.tsx
import { Loader2Icon } from 'lucide-solid'
import { createSignal, Show } from 'solid-js'
import { Button } from './ui/button'
import { Panel, PanelHeader, PanelHeaderGroup, PanelTitle } from './ui/panel'
import { Textarea } from './ui/textarea'

interface CommitPanelProps {
  onCommit: (message: string) => Promise<boolean>
  loading: boolean
}

const MAX_SUBJECT_LENGTH = 72

export function CommitPanel(props: CommitPanelProps) {
  const [message, setMessage] = createSignal('')

  const handleCommit = async () => {
    const trimmed = message().trim()
    if (!trimmed) return
    const success = await props.onCommit(trimmed)
    if (success) setMessage('')
  }

  const subjectLength = () => (message().split('\n')[0] ?? '').length
  const subjectWarn = () => subjectLength() > MAX_SUBJECT_LENGTH

  return (
    <Panel class="flex-none">
      <PanelHeader>
        <PanelHeaderGroup>
          <PanelTitle>Commit</PanelTitle>
        </PanelHeaderGroup>
        <span
          class={`text-xs tabular-nums ${
            subjectWarn() ? 'text-destructive' : 'text-muted-foreground'
          }`}
        >
          {subjectLength()}/{MAX_SUBJECT_LENGTH}
        </span>
      </PanelHeader>

      <div class="flex flex-col gap-2.5 p-3">
        <Textarea
          value={message()}
          onInput={(event) => setMessage(event.currentTarget.value)}
          placeholder="Summarize the change in one line, then describe details below."
          rows={3}
          class="resize-none"
        />
        <div class="flex items-center justify-end">
          <Button size="sm" onClick={handleCommit} disabled={!message().trim() || props.loading}>
            <Show when={props.loading} fallback={'Commit Changes'}>
              <Loader2Icon class="animate-spin" />
              Committing...
            </Show>
          </Button>
        </div>
      </div>
    </Panel>
  )
}
