// src/renderer/solid/components/shell/RefTreeRow/Chevron.tsx
import { ChevronDownIcon, ChevronRightIcon } from 'lucide-solid'
import { Show } from 'solid-js'

export function Chevron(props: { expanded: boolean }) {
  return (
    <Show
      when={props.expanded}
      fallback={<ChevronRightIcon class="size-3 shrink-0 text-muted-foreground" />}
    >
      <ChevronDownIcon class="size-3 shrink-0 text-muted-foreground" />
    </Show>
  )
}

// src/renderer/features/refs/RefTreeRow/Chevron.tsx
import { ChevronDownIcon, ChevronRightIcon } from 'lucide-react'

export function Chevron(props: { expanded: boolean }) {
  return props.expanded ? (
    <ChevronDownIcon className="size-3 shrink-0 text-muted-foreground" />
  ) : (
    <ChevronRightIcon className="size-3 shrink-0 text-muted-foreground" />
  )
}
