// src/renderer/features/refs/RefTreeRow/index.tsx
import type { CSSProperties } from 'react'
import { refFilterKey } from '@/features/history/selectors'
import { REF_TREE_ROW_HEIGHT, type RefKind, type RefRow } from '@/features/refs/ref-tree'
import type { BranchAction, StashAction } from '@/lib/git-actions'
import { EmptyRow } from './EmptyRow'
import { FolderRow } from './FolderRow'
import { LeafRow } from './LeafRow'
import { SectionRow } from './SectionRow'
import { SkeletonRowItem } from './SkeletonRow'
import { StashRow } from './StashRow'

interface RefTreeRowProps {
  row: RefRow
  top: number
  localLoading: boolean
  currentBranch?: string
  visibleTimelineRefs?: ReadonlySet<string>
  onToggleCollapsed: (key: string) => void
  onToggleTimelineVisibility?: (refKind: RefKind, fullPath: string) => void
  onCheckoutLeaf?: (refKind: RefKind, fullPath: string) => void
  onBranchAction?: (action: BranchAction, refKind: RefKind, fullPath: string) => void
  onStashAction?: (action: StashAction, index: number, expectedOid: string) => void
}

export function RefTreeRow(props: RefTreeRowProps) {
  const baseStyle: CSSProperties = {
    top: '0',
    height: `${REF_TREE_ROW_HEIGHT}px`,
    transform: `translateY(${props.top}px)`,
    contain: 'layout paint style'
  }

  switch (props.row.kind) {
    case 'section':
      return (
        <SectionRow
          row={props.row}
          style={baseStyle}
          loading={props.localLoading && props.row.refKind === 'local'}
          onToggleCollapsed={props.onToggleCollapsed}
        />
      )
    case 'empty':
      return <EmptyRow row={props.row} style={baseStyle} />
    case 'skeleton':
      return <SkeletonRowItem row={props.row} style={baseStyle} />
    case 'folder':
      return (
        <FolderRow row={props.row} style={baseStyle} onToggleCollapsed={props.onToggleCollapsed} />
      )
    case 'stash':
      return <StashRow row={props.row} style={baseStyle} onStashAction={props.onStashAction} />
    case 'leaf':
      return (
        <LeafRow
          row={props.row}
          style={baseStyle}
          currentBranch={props.currentBranch}
          onBranchAction={props.onBranchAction}
          timelineVisible={
            props.visibleTimelineRefs?.has(refFilterKey(props.row.refKind, props.row.fullPath)) ??
            false
          }
          onToggleTimelineVisibility={props.onToggleTimelineVisibility}
          onCheckoutLeaf={props.onCheckoutLeaf}
        />
      )
  }
}

// src/renderer/components/shell/RefTreeRow/index.tsx
import { type JSX, Match, Switch } from 'solid-js'
import { refFilterKey } from '@/components/HistoryPanel/selectors'
import { REF_TREE_ROW_HEIGHT, type RefKind, type RefRow } from '@/lib/ref-tree'
import { EmptyRow } from './EmptyRow'
import { FolderRow } from './FolderRow'
import { LeafRow } from './LeafRow'
import { SectionRow } from './SectionRow'
import { SkeletonRowItem } from './SkeletonRow'

interface RefTreeRowProps {
  row: RefRow
  top: number
  localLoading: boolean
  visibleTimelineRefs?: ReadonlySet<string>
  onToggleCollapsed: (key: string) => void
  onToggleTimelineVisibility?: (refKind: RefKind, fullPath: string) => void
  onCheckoutLeaf?: (refKind: RefKind, fullPath: string) => void
}

export function RefTreeRow(props: RefTreeRowProps) {
  const baseStyle = (): JSX.CSSProperties => ({
    top: '0',
    height: `${REF_TREE_ROW_HEIGHT}px`,
    transform: `translateY(${props.top}px)`,
    contain: 'layout paint style'
  })

  return (
    <Switch>
      <Match when={props.row.kind === 'section'}>
        <SectionRow
          row={props.row as Extract<RefRow, { kind: 'section' }>}
          style={baseStyle()}
          loading={props.localLoading && props.row.refKind === 'local'}
          onToggleCollapsed={props.onToggleCollapsed}
        />
      </Match>
      <Match when={props.row.kind === 'empty'}>
        <EmptyRow row={props.row as Extract<RefRow, { kind: 'empty' }>} style={baseStyle()} />
      </Match>
      <Match when={props.row.kind === 'skeleton'}>
        <SkeletonRowItem
          row={props.row as Extract<RefRow, { kind: 'skeleton' }>}
          style={baseStyle()}
        />
      </Match>
      <Match when={props.row.kind === 'folder'}>
        <FolderRow
          row={props.row as Extract<RefRow, { kind: 'folder' }>}
          style={baseStyle()}
          onToggleCollapsed={props.onToggleCollapsed}
        />
      </Match>
      <Match when={props.row.kind === 'leaf'}>
        <LeafRow
          row={props.row as Extract<RefRow, { kind: 'leaf' }>}
          style={baseStyle()}
          timelineVisible={
            props.visibleTimelineRefs?.has(
              refFilterKey(
                (props.row as Extract<RefRow, { kind: 'leaf' }>).refKind,
                (props.row as Extract<RefRow, { kind: 'leaf' }>).fullPath
              )
            ) ?? false
          }
          onToggleTimelineVisibility={props.onToggleTimelineVisibility}
          onCheckoutLeaf={props.onCheckoutLeaf}
        />
      </Match>
    </Switch>
  )
}
